-- CreateTable
CREATE TABLE "PYQ" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "question" TEXT NOT NULL,
    "answer" TEXT NOT NULL,
    "examId" INTEGER NOT NULL,
    "yearId" INTEGER NOT NULL,
    CONSTRAINT "PYQ_examId_fkey" FOREIGN KEY ("examId") REFERENCES "Exam" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PYQ_yearId_fkey" FOREIGN KEY ("yearId") REFERENCES "ExamYear" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
